### ISSUE TITLE
Can't deploy any smart contracts on any testnet chains

### ISSUE THREAD

**Issue by cm-stratton** [skalenetwork/skaled#1924] opened 2024-06-13 02:10 UTC
![image](https://github.com/skalenetwork/skaled/assets/165963250/af4bab41-dc70-457d-a698-2d0aec244a62)

**Comment by DmytroNazarenko** [comment] 2024-06-14 19:10
Hey @cm-stratton ! The problem was related to the testnet proxy (there was no free space on the instance), now it should be fixed. Could you check whether the problem is still relevant?

**Comment by TheGreatAxios** [comment] 2024-09-12 21:37
Closing due to previous resolution by increasing space on instance.

**Closed as completed by TheGreatAxios** 2024-09-12 21:37 UTC
