### ISSUE TITLE
Inconsistent revertReason between skaled and geth

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1760] opened 2023-12-15 15:34 UTC
**Preconditions**
Active chains
Archival node
Address with Sfuel and with Whitelist deployer role
Deployed contract with erc20 tokens
[Example ERC20](https://github.com/skalenetwork/test-tokens/blob/develop/contracts/ERC20Custom.sol)

**Versions**
skalenetwork/schain:3.17.2-develop.2-historic

**Steps to reproduce**
1. Mint 100 tokens to UserA
2. Send 1 transaction (!only 1 transaction in block) token transfer from UserA to UserB that is expected to fail - send 200 Tokens (Insufficient balance)
3. Wait until the transaction is mined with 0x0 status and with the Revert reason and save the block hash
4. Send debug_traceBlockByHash method with 4 Geth tracers 
```
"callTracer", "4byteTracer", "prestateTracer",
                   "noopTracer", "replayTracer", "allTracer"
```

**Expected state:**
Revert reason should be a human-readable string
```
revertReason":"INSUFFICIENT BALANCE"
```

**Actual state:**
Revert reason  is the binary string 
```
"revertReason":"\bù�\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0014Insufficient balance\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
```

Example 
```
"jsonrpc": "2.0",
        "method": "debug_traceBlockByHash",
        "params": [
            "0x24624be7dc347d1db1eaec4b0294df06cb67a9a27040e0046fe6df2c94db0f22",
            {"tracer": "callTracer"}
        ],
        "id": 1
    }

Response traceBlockByNumber: {"id":1,"jsonrpc":"2.0","result":[{"result":{"from":"0xfeaf25fa746e313d01615c0be24e801622044ec4","gas":"0x02af40","gasUsed":"0x64bc","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b4000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","revertReason":"\bù�\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0014Insufficient balance\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","to":"0x65df8100ea2826e54c49acca77d534ae06f4cee5","type":"CALL","value":"0x"},"txHash":"0x4d5d501c26eba93be389436e3c78159ad71d094cf03b43700a446d0892bdba37"}]}
```

**Comment by kladkogex** [comment] 2024-01-04 19:17
Closing this since its not a bug, the code does not include require with ""INSUFFICIENT BALANCE" string

**Comment by oleksandrSydorenkoJ** [comment] 2024-01-05 08:53
> Closing this since its not a bug, the code does not include require with ""INSUFFICIENT BALANCE" string

example on the Goerli  with the same contract. 

https://goerli.etherscan.io/tx/0x4ad33171602de75bfa2438a577bcd2a21aba1d89bac3081fc78dd126e41613b7
and response on debug_traceBlockByHash request
```

"error":"execution reverted","revertReason":"Insufficient balance",


{"txHash":"0x4ad33171602de75bfa2438a577bcd2a21aba1d89bac3081fc78dd126e41613b7","result":{"from":"0xfeaf25fa746e313d01615c0be24e801622044ec4","gas":"0x30d40","gasUsed":"0x69d0","to":"0xac29fed5f070c26ffd007c1009b8861fbf2ece72","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b4000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014496e73756666696369656e742062616c616e6365000000000000000000000000","error":"execution reverted","revertReason":"Insufficient balance","value":"0x0","type":"CALL"}}
```

**Closed as completed** 2024-03-05 11:20 UTC
Labels: bug, epic:archive-node

**Comment by oleksandrSydorenkoJ** [comment] 2024-03-27 13:12
Blocked by https://github.com/skalenetwork/skaled/issues/1526

**Comment by oleksandrSydorenkoJ** [comment] 2024-05-02 13:36
Verified on legacy network
skale_schain_these-long-sadalsuud
skalenetwork/schain:3.18.1-beta.0-historic
Block 299549


```
 curl ttp://localhost:10195/   -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceBlockByHash","params":["0xf8152326594f579518ce649e7e716d034feed4eb3993a4b5ef5f8811dd7f367e", {"tracer": "callTracer"}], "id":1,"jsonrpc":"2.0"}'
{"id":1,"jsonrpc":"2.0","result":[{"result":{"error":"execution reverted","from":"0x482d7f53cba6ae73a354533673c48e2dfd560949","gas":"0x30d40","gasUsed":"0x64bc","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014496e73756666696369656e742062616c616e6365000000000000000000000000","revertReason":"Insufficient balance","to":"0x8722eb776a5d9a2ffd914648381fe2daf80c7add","type":"CALL","value":"0x0"},"txHash":"0x6f2af81740fbd00b2dc808aebed08cd9191e26c20c518506c81069056ba4a5a2"},{"result":{"from":"0xe3cc6ec63b5652d1594bc63bb293f4e80f76dbdd","gas":"0x30d40","gasUsed":"0x19062","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x0000000000000000000000000000000000000000000000000000000000000001","to":"0x8722eb776a5d9a2ffd914648381fe2daf80c7add","type":"CALL","value":"0x0"},"txHash":"0x652cdca90b236cc37d4ce2b5b0ed9072c510468e6dfef40b48fca7c5c1512c6e"},{"result":{"error":"execution reverted","from":"0xa6d50055592cecb795bc1ed3b9ea57ed426b0b7c","gas":"0x30d40","gasUsed":"0x64bc","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014496e73756666696369656e742062616c616e6365000000000000000000000000","revertReason":"Insufficient balance","to":"0x8722eb776a5d9a2ffd914648381fe2daf80c7add","type":"CALL","value":"0x0"},"txHash":"0x7c9dbb1c7e8908d83175c9d40e0ffb536710cffb09bcb7fe790ea56e4d1459f6"},{"result":{"from":"0x3f5bdf5d4c274c82b8d17aa2810b00d2cf050f24","gas":"0x30d40","gasUsed":"0x19062","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x0000000000000000000000000000000000000000000000000000000000000001","to":"0x8722eb776a5d9a2ffd914648381fe2daf80c7add","type":"CALL","value":"0x0"},"txHash":"0xcf96aa12d56275dc3e2e9e2daee6693d2bad1efd7493a99d3eeaa4b88f2a2688"},{"result":{"from":"0x94c6e5746971d6aebeaa42cbbe2feca0f6b5b24f","gas":"0x30d40","gasUsed":"0x19062","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x0000000000000000000000000000000000000000000000000000000000000001","to":"0x8722eb776a5d9a2ffd914648381fe2daf80c7add","type":"CALL","value":"0x0"},"txHash":"0x98a708626a82498451b8183ec2609cd1d1eee5d0ec5949651ceba68387a79a43"},{"result":{"error":"execution reverted","from":"0xb70603c505f85130b5b2e73cd82d196dfd7d8b5e","gas":"0x30d40","gasUsed":"0x64bc","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014496e73756666696369656e742062616c616e6365000000000000000000000000","revertReason":"Insufficient balance","to":"0x8722eb776a5d9a2ffd914648381fe2daf80c7add","type":"CALL","value":"0x0"},"txHash":"0xd0258d700e644bf2f66bfc1eeb3ea2982fc658efdd14a3b378bcd72ba8e70b58"},{"result":{"error":"execution reverted","from":"0xbf5aa678b969c0871e2fbcf09c3dbb5d5865ac1e","gas":"0x30d40","gasUsed":"0x64bc","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014496e73756666696369656e742062616c616e6365000000000000000000000000","revertReason":"Insufficient balance","to":"0x8722eb776a5d9a2ffd914648381fe2daf80c7add","type":"CALL","value":"0x0"},"txHash":"0xcde552781f7096bd310d35367bd12f4df42eea8752f8db048d79f934f08b1023"},{"result":{"error":"execution reverted","from":"0x079cf317ef40b16141784b6fabff812d64f7c0fd","gas":"0x30d40","gasUsed":"0x64bc","input":"0x56b8c7240000000000000000000000007cef6369dfd5377d823a2c65b3c2de740d52a5b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008366393063613830343832303136623833303138366130393438386664356530313037383632396363313934633933336439363331623934342020202020202020202020202020386665313062316438306239306334343764393330313962303030303033306365653739333865396562613265393132313162373862333239653236320000000000000000000000000000000000000000000000000000000000","output":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014496e73756666696369656e742062616c616e6365000000000000000000000000","revertReason":"Insufficient balance","to":"0x8722eb776a5d9a2ffd914648381fe2daf80c7add","type":"CALL","value":"0x0"},"txHash":"0xacfdd073d859caefdb41150abad37f82de013206b73c214a5416105485e65ee3"}]
```

**Comment by PolinaKiporenko** [comment] 2024-05-02 14:08
3.18.1-beta.0
