### ISSUE TITLE
Skaled crashes under significant load with MTM

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1542] opened 2023-06-14 16:33 UTC
**Version:**
skalenetwork/schain:3.16.0-stable.3

**Preconditions:**
Active Skale-chain medium type with enabled MTM
all nodes active and mining blocks
Amount of accounts = 1000 
All accounts have 3 sFuel on balance
MTM amount = 10

**Steps to reproduce:**
1. Run load tests to 16 endpoints
2. Wait for 1-2 hours
3. Check skaled containers on the core nodes

**Expected state:**
Skaled should mining blocks without any crashes 

**Actual state:**
Skaled crashes without errors. After restarting skaled container by admin, skaled continue mining blocks.

**Logs:**
[crash_skaled_under_load.txt](https://github.com/skalenetwork/skaled/files/11748506/crash_skaled_under_load.txt)

**Comment by kladkogex** [comment] 2023-06-16 12:16
Marking P1 as this is a crash

**Comment by kladkogex** [comment] 2023-06-18 22:49
I think I figured out what the problem is - assigning it to myself

**Comment by kladkogex** [comment] 2023-07-05 18:01
Reassigning this to @dimalit since Dima is saying that there is no problem with iterators.

There is something segfaulting inside the queue

**Comment by dimalit** [comment] 2023-07-06 14:21
Need to find version on which crash was occurring, and try to fix it with
https://github.com/skalenetwork/skale-consensus/pull/800/files
or maybe with
https://github.com/skalenetwork/skale-consensus/pull/799/files

**Comment by DmytroNazarenko** [comment] 2023-12-07 15:21
skaled: 3.17.1

**Closed as completed by DmytroNazarenko** 2023-12-07 15:21 UTC
Labels: bug, P1, skaled, epic:HPD

**Comment by oleksandrSydorenkoJ** [comment] 2024-01-08 16:11
should be fixed with https://github.com/skalenetwork/skaled/issues/1588

**Comment by oleksandrSydorenkoJ** [comment] 2024-02-28 18:00
This issue is the result of the memory leaks and should be fixed at https://github.com/skalenetwork/internal-support/issues/931
